[theme]
theme = "solarized-dark"

[icons]
icons = "emoji"

[[block]]
block = "backlight"

[[block]]
block = "disk_space"
path = "/"
alert_unit = "GB"
format = " $icon NVME0 {$free}"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization "

[[block]]
block = "temperature"

[[block]]
block = "memory"
#display_type = "memory"
format = " $icon {$mem_used}/{$mem_total}({$mem_used_percents})"
#clickable = false

[[block]]
block = "net"
device = "wlan0"
format = " ^icon_net_wireless {$ssid|} {$bitrate|}"
missing_format = ""

[[block]]
block = "net"
device = "wg0"
format = " ^icon_net_vpn {$graph_down}"
missing_format = ""

[[block]]
block = "sound"

[[block]]
block = "battery"
#show = "both"
format = " $icon $percentage {$time |}"
full_format = " $icon $percentage {$time |}"
empty_format = " $icon $percentage {$time |}"
charging_format = " $icon $percentage {$time |}"
not_charging_format = " $icon $percentage {$time |}"
device = "BAT0"

[[block]]
block = "time"
interval = 60
format = " $timestamp.datetime(f:'%Y/%m/%d %a %R')"
#command_on = "orage"
