theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "backlight"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "net"
device = "wlp0s20f3"
ssid = true
hide_inactive = true
hide_missing = true

[[block]]
block = "net"
device = "tinc0"
ip = true
speed_up = false
speed_down = false
hide_inactive = true
hide_missing = true

[[block]]
block = "sound"

[[block]]
block = "battery"
show = "both"
device = "CMB0"

[[block]]
block = "time"
interval = 60
format = "%a %Y/%m/%d %R"
